# .github/workflows/ci-testing.yml
name: Backend CI - Build and Push Images to ACR

on:
  push:
    branches: [ "testing" ]
    paths: [ "backend/**" ]
  workflow_dispatch:

env:
  ACR_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY }}                # short name, e.g. myregistry
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name ${{ env.ACR_NAME }}

      # Customer Service
      - run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:latest \
                       ./backend/customer_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:latest

      # Product Service
      - run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest \
                       ./backend/product_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest

      # Order Service
      - run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest \
                       ./backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest

      - run: az logout
        if: always()
