# .github/workflows/ci-testing.yml
name: Backend CI - Build and Push Images to ACR

on:
  push:
    branches: [ "testing" ]      # Trigger only on 'testing' branch
    paths: [ "backend/**" ]
  workflow_dispatch:             # Allow manual trigger

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name ${{ env.ACR_LOGIN_SERVER }}

      # Build & Push Customer Service
      - run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/customer_service:latest \
                       ./backend/customer_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/customer_service:latest

      # Build & Push Product Service
      - run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/product_service:latest \
                       ./backend/product_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/product_service:latest

      # Build & Push Order Service
      - run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }} \
                       -t ${{ env.ACR_LOGIN_SERVER }}/order_service:latest \
                       ./backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:${{ env.IMAGE_TAG }}
          docker push ${{ env.ACR_LOGIN_SERVER }}/order_service:latest

      - run: az logout
        if: always()
